### PR TITLE
Update the document on base url selection for Api calls

### PR DESCRIPTION
**Pull request by JagadeeshMaroju**
Updating the document to make sure user picks the proper base url for their API calls.

### CODE REVIEW

**Review by robertsoniv — CHANGES_REQUESTED** [review]
Based on the region and environment selected when your (single word) marketplace was first created.

**Review by robertsoniv — CHANGES_REQUESTED** [review]
Sorry I didn't notice this the first time around but we'd rather have the images needed for our content come from within this repository. You should be able to add this image to your PR in [this folder](https://github.com/ordercloud-api/oc-documentation/tree/fb5cd26a2dbfe6e261c68b0d4aa170d73295eba2/static/images/learn/getting-started), and reference it like so:

```
![image title](/images/learn/getting-started/new-image-name.jpg)
```

Also, one more wording change for the beginning of that sentence:

"The base URL is determined by the selected region and environment when first creating your marketplace."

Trying to avoid "base url will get changed" language because technically that URL will _never_ change once the marketplace is created.

**Review by robertsoniv — APPROVED** [review]

**Comment by robertsoniv** [comment]
Thanks for the quick updates @JagadeeshMaroju !  Appreciate it

**Comment by JagadeeshMaroju** [comment]
Thank you @robertsoniv.

**Pull request merged**
